FROM node:18

WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

COPY src/app/lib/parsers/requirements.txt ./
RUN pip3 install -r requirements.txt --break-system-packages

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]